#server:
#  port: 8080
#  servlet:
#    context-path: /hot

dir:
  # 学习tomcat目录
  shared:
  # 此目录下，每个文件夹都是单独的内容
  exclude: /Users/liufeng/Documents/clazz/biz


elasticsearch:
  host: ["http://127.0.0.1:9200"]
server:
  host: "0.0.0.0"
  shutdownTimeout: "5s"
monitoring:
  ui:
    container:
      elasticsearch:
        enabled: true